[package]
name = "test_tarpaulin_env"
version = "0.1.0"
authors = ["pinkforest <36498018+pinkforest@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

